spring:
  redis:
    host: 127.0.0.1
    port: 16379
    password: root
    database: 5
    timeout: 5000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/stock_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      database: 5
      password: root
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 16
          max-wait: -1ms
          max-idle: 8
          min-idle: 2
logging:
  level:
    com.cloud.stock: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.cloud.openfeign: debug
    com.alibaba.nacos: warn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  production: false
  basic:
    enable: false






