spring:
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:root}
      database: ${REDIS_DATABASE:6}
      timeout: ${REDIS_TIMEOUT:5000ms}
      lettuce:
        pool:
          max-active: 16
          max-wait: -1ms
          max-idle: 8
          min-idle: 2
logging:
  level:
    com.cloud.gateway: debug
    org.springframework.cloud.gateway: debug
    org.springframework.security: debug
    org.springframework.web: debug
    com.alibaba.nacos: warn
app:
  security:
    enable-test-api: true
knife4j:
  enable: true
  production: false
  basic:
    enable: false



