# ASCII comment sanitized for compatibility.
global:
  scrape_interval: 15s # ASCII comment sanitized for compatibility.
  evaluation_interval: 15s # ASCII comment sanitized for compatibility.

# ASCII comment sanitized for compatibility.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# ASCII comment sanitized for compatibility.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# ASCII comment sanitized for compatibility.
scrape_configs:
  # ASCII comment sanitized for compatibility.
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090' ]

  # ASCII comment sanitized for compatibility.
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:80' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8081' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8082' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8083' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8084' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8085' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8086' # ASCII comment sanitized for compatibility.
          - 'host.docker.internal:8087' # ASCII comment sanitized for compatibility.
    scrape_interval: 10s

