# 兼容性注释已标准化。
global:
  scrape_interval: 15s # 兼容性注释已标准化。
  evaluation_interval: 15s # 兼容性注释已标准化。

# 兼容性注释已标准化。
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 兼容性注释已标准化。
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# 兼容性注释已标准化。
scrape_configs:
  # 兼容性注释已标准化。
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090' ]

  # 兼容性注释已标准化。
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8081' # 兼容性注释已标准化。
          - 'host.docker.internal:8082' # 兼容性注释已标准化。
          - 'host.docker.internal:8083' # 兼容性注释已标准化。
          - 'host.docker.internal:8084' # 兼容性注释已标准化。
          - 'host.docker.internal:8085' # 兼容性注释已标准化。
          - 'host.docker.internal:8086' # 兼容性注释已标准化。
          - 'host.docker.internal:8087' # 兼容性注释已标准化。
    scrape_interval: 10s


