spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://127.0.0.1:19200}
    username:
    password:
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:root}
      database: ${REDIS_DATABASE:7}
      timeout: ${REDIS_TIMEOUT:6000ms}
      lettuce:
        pool:
          max-active: 16
          max-wait: -1ms
          max-idle: 8
          min-idle: 2
cache:
  multi-level:
    enabled: true
    l1:
      type: caffeine
      caffeine:
        maximum-size: 1000
        expire-after-write: 5m
    l2:
      type: redis
      redis:
        time-to-live: 30m
logging:
  level:
    com.cloud.search: debug
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.cloud.openfeign: debug
    org.elasticsearch: debug
    com.alibaba.nacos: warn
knife4j:
  enable: true
  production: false
  basic:
    enable: false



